-------------------------------------------------------------------------------
-- SQL Script generated by FormSync 9.1.0.9 As of 20/07/2014 09:48 a.m.
-- Source Configuration: Barugel_Forms
-- Objects Scripted:
--   ArgentineanStrings: fZRT_BankPayType, sZrtFiscalCode, sZrtFiscalName
-------------------------------------------------------------------------------
DECLARE @FormID int
DELETE FROM [ColombianStrings] WHERE [Name] = N'fZRT_BankPayType' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 

INSERT INTO [ColombianStrings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'fZRT_BankPayType', N'Relaciones entre Bancos de 3ros y Medios de Pago', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [ColombianStrings] WHERE [Name] = N'sZrtFiscalCode' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 

INSERT INTO [ColombianStrings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sZrtFiscalCode', N'Documento', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [ColombianStrings] WHERE [Name] = N'sZrtFiscalName' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 

INSERT INTO [ColombianStrings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sZrtFiscalName', N'Denom Fiscal', NULL, NULL, 1, N'[NULL]', NULL)

-------------------------------------------------------------------------------
DELETE FROM [ColombianStrings] WHERE [Name] = N'fZPV_CoDiscountControl' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 

INSERT INTO [ColombianStrings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'fZPV_CoDiscountControl', N'Control de Descuentos POS', NULL, NULL, 1, N'[NULL]', NULL)

-------------------------------------------------------------------------------
DELETE FROM [ColombianStrings] WHERE [Name] = N'fZPV_Convenios' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 

INSERT INTO [ColombianStrings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'fZPV_Convenios', N'Convenios', NULL, NULL, 1, N'[NULL]', NULL)

-------------------------------------------------------------------------------
DELETE FROM [ColombianStrings] WHERE [Name] = N'fZPV_Follow' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 

INSERT INTO [ColombianStrings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'fZPV_Follow', N'Codigos de Seguimiento de Pedidos', NULL, NULL, 1, N'[NULL]', NULL)

