-------------------------------------------------------------------------------
-- SQL Script generated by FormSync 9.1.0.21 As of 26/04/2015 18:50
-- Source Configuration: ELDORADO_Forms
-------------------------------------------------------------------------------
DECLARE @FormID int
DELETE FROM PropertyDefaults WHERE [PropertyName] = N'UserDefinedType' AND [IsPropertyClassExtension] = 0 AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 

DELETE FROM PropertyDefaultDragDropEvents WHERE [PropertyName] = N'UserDefinedType' AND [IsPropertyClassExtension] = 0 AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 

INSERT INTO PropertyDefaults ( 
 [PropertyName], [ScopeType], [ScopeName], 
 [Description], [Label], [ListSource], 
 [FindFromForm], [FindFromProperty], [MaintainFromSpec], 
 [Validators], [MaxCharacters], [ValidateImmediately], [ValueIsListIndex], 
 [LockedBy], [DataType], [IsPropertyClassExtension], [Flags], [ComponentFlags], 
 [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], 
 [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
 [Post301DataType], [Post301Format] ) 
VALUES ( 
 N'UserDefinedType', 1, N'[NULL]', 
 N'Parm: name of type; use this for standard facilities for value corresponding to a user-defined type', NULL, N'STDOLE MGCore.UserDefinedTypeValues(  PROPERTIES( Value, Description ) DISPLAY(1,2)FILTER(TypeName = ''%1''))', 
 N'UserDefinedTypeValuesQuery( FILTERPERM( TypeName = ''%1'' ) )', N'Value', N'UserDefinedTypeValues( FILTERPERM( TypeName = ''%1'' ) SETVARVALUES( TypeName=%1 ) )', 
 N'UserDefinedTypeValue(%1)', 0, 1, 0, 
 NULL, NULL, 0, 0, 0, 
 NULL, NULL, NULL, NULL, 
 NULL, NULL, 0, N'StdDetailsAddFind', 
 NULL, N'AUTOIME(NoControl)' ) 


