-------------------------------------------------------------------------------
-- SQL Script generated by FormSync 9.1.0.21 As of 26/04/2015 18:50
-- Source Configuration: ELDORADO_Forms
-------------------------------------------------------------------------------
DECLARE @FormID int
DELETE FROM PropertyDefaults WHERE [PropertyName] = N'Item' AND [IsPropertyClassExtension] = 0 AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 

DELETE FROM PropertyDefaultDragDropEvents WHERE [PropertyName] = N'Item' AND [IsPropertyClassExtension] = 0 AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 

INSERT INTO PropertyDefaults ( 
 [PropertyName], [ScopeType], [ScopeName], 
 [Description], [Label], [ListSource], 
 [FindFromForm], [FindFromProperty], [MaintainFromSpec], 
 [Validators], [MaxCharacters], [ValidateImmediately], [ValueIsListIndex], 
 [LockedBy], [DataType], [IsPropertyClassExtension], [Flags], [ComponentFlags], 
 [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], 
 [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
 [Post301DataType], [Post301Format] ) 
VALUES ( 
 N'Item', 1, N'[NULL]', 
 NULL, NULL, N'STDOLE SL.SLItems(  PROPERTIES(Item, Description, LotTracked, UM, TaxFreeMatl, ActiveForCustomerPortal, Overview, DimensionGroup, TrackPieces, LotPrefix) DISPLAY(1,2)FILTER(ShowInDropDownList=1)ORDERBY(Item))', 
 N'ItemsQuery(PROPERTY(Item) FINDSETPROP(%1=Description))', NULL, N'Items(PROPERTY(Item) FINDSETPROP(%1=Description))', 
 N'Item(%1,%2,%3,%4,%5,%6,%7),DefaultStartingToEnding(%8,%9)', 0, 1, 0, 
 NULL, NULL, 0, 0, 0, 
 N'ItemChanged', N'EnableDisable', NULL, NULL, 
 NULL, NULL, 0, N'StdDetailsAddFind', 
 N'DATATYPE(CHAR)', N'AUTOIME(NoControl)' ) 


