-------------------------------------------------------------------------------
-- SQL Script generated by FormSync 9.1.0.21 As of 26/04/2015 18:50
-- Source Configuration: ELDORADO_Forms
-------------------------------------------------------------------------------
DECLARE @FormID int
SET @FormID = NULL
SELECT @FormID = Forms.ID FROM Forms WHERE [Name] = N'ZPV_ShipCodes' AND [ScopeType] = 1
IF @FormID IS NOT NULL
BEGIN
   DELETE FROM Forms WHERE ID = @FormID
   DELETE FROM FormEventHandlers WHERE FormID = @FormID
   DELETE FROM FormComponents WHERE FormID = @FormID
   DELETE FROM ActiveXComponentProperties WHERE FormID = @FormID
   DELETE FROM Variables WHERE FormID = @FormID
   DELETE FROM FormComponentDragDropEvents WHERE FormID = @FormID
   DELETE FROM DerivedFormOverrides WHERE FormID = @FormID
END
INSERT INTO [Forms] (
  [ScopeType], [ScopeName], [Component], [Name], [SubComponent], [Type], [Caption], 
  [PrimaryDataSource], 
  [StandardOperations], [TopPos], [LeftPos], [Height], [Width], [IconFileName], [HelpFileName], [HelpContextID], [Flags], [LockedBy], 
  [FilterFormSpec], [PaneZeroSize], [Description], [MasterDeviceID], [BaseFormName] ) 
VALUES ( 
  1, N'[NULL]', NULL, N'ZPV_ShipCodes', NULL, 1, N'fShipViaCodes', 
  N'SL.SLShipcodes( OBJNAME(Objects) )', 
  1019, CAST('0' AS float), CAST('0' AS float), CAST('22' AS float), CAST('87' AS float), N'FORMICON() FORMWALLPAPER()', N'default.html?helpcontent=mergedProjects/sl_custvend/forms/cotopics/ship_via_codes.htm', -1, 10, N'sa', 
  NULL, N'17.142857142857142', NULL, 0, NULL)
SELECT @FormID = Forms.ID FROM Forms WHERE [Name] = N'ZPV_ShipCodes' AND [ScopeType] = 1
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'ActiveForPortalCheckBox', -1, 
  5, 5, CAST('3.1266666666666665' AS float), CAST('21.142857142857142' AS float), CAST('1.2666666666666666' AS float), CAST('2' AS float), CAST('18.571428571428573' AS float), NULL, 
  NULL, 
  NULL, 0, N'object.ActiveForCustomerPortal', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  1, NULL, 0, 0, NULL, NULL, N'default.html?helpcontent=mergedProjects/sl_main/fields/a/active_cust_portal_currency_codes.htm', -1, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, N'ListYesNo', 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sActiveForPortal')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'ActiveForPortalGridCol', -1, 
  7, 15, CAST('0' AS float), CAST('72.857142857142861' AS float), CAST('6.666666666666667' AS float), CAST('2' AS float), CAST('14.285714285714287' AS float), NULL, 
  NULL, 
  N'FormCollectionGrid', 6, N'object.ActiveForCustomerPortal', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  8, NULL, 0, 0, NULL, NULL, N'default.html?helpcontent=mergedProjects/sl_main/fields/a/active_cust_portal_currency_codes.htm', -1, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, N'ListYesNo', 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sActiveForPortal')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'CarrierCol', -1, 
  4, 15, CAST('0' AS float), CAST('16.142857142857142' AS float), CAST('6.666666666666667' AS float), CAST('2' AS float), CAST('17' AS float), NULL, 
  NULL, 
  N'FormCollectionGrid', 3, N'object.CarrierCode', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 0, NULL, NULL, N'default.html?helpcontent=mergedProjects/sl_custvend/fields/c/carrier_code_ship_via_codes.htm', -1, NULL, 
  NULL, NULL, NULL, 
  N'0', N'CarrierCode(CarrierName)', NULL, NULL, N'CarrierCode', 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sCarrierCode')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'CarrierDescriptionEdit', -1, 
  11, 1, CAST('8.5' AS float), CAST('21.142857142857142' AS float), CAST('1.3' AS float), CAST('2' AS float), CAST('44.399999999999999' AS float), NULL, 
  NULL, 
  NULL, 0, N'object.CarrierName', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  1, NULL, 1, 1, NULL, NULL, N'default.html?helpcontent=mergedProjects/sl_custvend/fields/c/carrier_name_ship_via_codes.htm', -1, N'StdDefault', 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, N'Name', 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sName')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'CarrierEdit', -1, 
  10, 27, CAST('7' AS float), CAST('21.142857142857142' AS float), CAST('1.3' AS float), CAST('2' AS float), CAST('18' AS float), N'C(CarrierStatic)', 
  NULL, 
  NULL, 0, N'object.CarrierCode', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  1, NULL, 1, 1, NULL, NULL, N'default.html?helpcontent=mergedProjects/sl_custvend/fields/c/carrier_code_ship_via_codes.htm', -1, NULL, 
  NULL, NULL, NULL, 
  N'0', N'CarrierCode(CarrierName)', NULL, NULL, N'CarrierCode', 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'C(CarrierStatic)')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'CarrierNameGridCol', -1, 
  5, 15, CAST('0' AS float), CAST('33.142857142857146' AS float), CAST('6.666666666666667' AS float), CAST('2' AS float), CAST('25.428571428571427' AS float), NULL, 
  NULL, 
  N'FormCollectionGrid', 4, N'object.CarrierName', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 1, 0, NULL, NULL, N'default.html?helpcontent=mergedProjects/sl_custvend/fields/c/carrier_name_ship_via_codes.htm', -1, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, N'Name', 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sName')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'CarrierServiceTypeCol', -1, 
  6, 15, CAST('0' AS float), CAST('58.571428571428569' AS float), CAST('6.666666666666667' AS float), CAST('2' AS float), CAST('14.285714285714287' AS float), NULL, 
  NULL, 
  N'FormCollectionGrid', 5, N'object.CarrierServiceType', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 0, NULL, NULL, N'default.html?helpcontent=mergedProjects/sl_custvend/fields/c/carrier_service_type_ship_via_codes.htm', -1, N'StdDefault', 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, N'CarrierServiceType', 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sCarrierServiceType')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'CarrierServiceTypeEdit', -1, 
  13, 1, CAST('10' AS float), CAST('21.142857142857142' AS float), CAST('1.3' AS float), CAST('2' AS float), CAST('12' AS float), N'C(CarrierServiceTypeStatic)', 
  NULL, 
  NULL, 0, N'object.CarrierServiceType', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  1, NULL, 1, 1, NULL, NULL, N'default.html?helpcontent=mergedProjects/sl_custvend/fields/c/carrier_service_type_ship_via_codes.htm', -1, N'StdDefault', 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, N'CarrierServiceType', 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'C(CarrierServiceTypeStatic)')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'CarrierServiceTypeStatic', -1, 
  12, 0, CAST('10.300000000000001' AS float), CAST('0.71428571428571275' AS float), CAST('1' AS float), CAST('2' AS float), CAST('19.714285714285715' AS float), NULL, 
  NULL, 
  NULL, 0, NULL, 
  0, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  1, NULL, 1, 1, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl) JUSTIFY(R)', 
  NULL, N'sCarrierServiceType')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'CarrierStatic', -1, 
  9, 0, CAST('7.2999999999999998' AS float), CAST('3.7142857142857126' AS float), CAST('1' AS float), CAST('2' AS float), CAST('16.714285714285715' AS float), NULL, 
  NULL, 
  NULL, 0, NULL, 
  0, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  1, NULL, 1, 1, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl) JUSTIFY(R)', 
  NULL, N'sCarrierCode')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'DescriptionEdit', -1, 
  4, 1, CAST('1.5966666666666667' AS float), CAST('20.714285714285715' AS float), CAST('1.3' AS float), CAST('2' AS float), CAST('42' AS float), N'C(DescriptionStatic)', 
  NULL, 
  NULL, 0, N'object.Description', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  1, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, N'Description', 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'C(DescriptionStatic)')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'DescriptionGridCol', -1, 
  2, 15, CAST('0' AS float), CAST('6.1428571428571432' AS float), CAST('15.199999999999999' AS float), CAST('2' AS float), CAST('32' AS float), NULL, 
  NULL, 
  N'FormCollectionGrid', 1, N'object.Description', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 0, NULL, NULL, N'default.html?helpcontent=mergedProjects/sl_custvend/fields/d/description_order_maintenanceship_via_codes.htm', -1, N'StdDefault', 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, N'Description', 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sDescription')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'FormCollectionGrid', -1, 
  0, 14, CAST('0' AS float), CAST('0' AS float), CAST('22' AS float), CAST('2' AS float), CAST('19' AS float), NULL, 
  NULL, 
  NULL, 0, N'objects', 
  3, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  16777600, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', N'StdGridWithActions()', NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, NULL)
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'GotoMaintenanceFolderToolbarButton', -1, 
  502, 11, CAST('0' AS float), CAST('0' AS float), CAST('0' AS float), CAST('0' AS float), CAST('0' AS float), N'sGoToMaintenanceFolder', 
  NULL, 
  NULL, 0, NULL, 
  0, N'GoToMaintenanceFolder', NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 0, N'GotoMaintenance.png', NULL, N'default.html?helpcontent=mergedProjects/sl_main/buttons/g/gotomaintenancefoldertoolbarbutton.htm', -1, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sGoToMaintenanceFolder')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'GotoQueriesFolderToolbarButton', -1, 
  505, 11, CAST('0' AS float), CAST('0' AS float), CAST('0' AS float), CAST('0' AS float), CAST('0' AS float), N'sGoToQueriesFolder', 
  NULL, 
  NULL, 0, NULL, 
  0, N'GoToQueriesFolder', NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 0, N'GotoQueries.png', NULL, N'default.html?helpcontent=mergedProjects/sl_main/buttons/g/gotoqueriesfoldertoolbarbutton.htm', -1, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sGoToQueriesFolder')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'GroupBox', -1, 
  1, 6, CAST('0.13' AS float), CAST('1' AS float), CAST('12' AS float), CAST('2' AS float), CAST('67.890000000000001' AS float), NULL, 
  NULL, 
  NULL, 0, NULL, 
  0, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  1, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', N'StdGroupBox()', NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, NULL)
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'InternationalCheckBox', -1, 
  6, 5, CAST('3.1266666666666665' AS float), CAST('48.428571428571423' AS float), CAST('1.2666666666666666' AS float), CAST('2' AS float), CAST('13.857142857142858' AS float), NULL, 
  NULL, 
  NULL, 0, N'object.International', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  1, NULL, 0, 0, NULL, NULL, N'default.html?helpcontent=mergedProjects/sl_custvend/fields/i/international_ship_via_codes.htm', -1, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, N'ListYesNo', 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sInternational')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'InternationalGridCol', -1, 
  8, 15, CAST('0' AS float), CAST('0' AS float), CAST('6.666666666666667' AS float), CAST('2' AS float), CAST('14.285714285714287' AS float), NULL, 
  NULL, 
  N'FormCollectionGrid', 7, N'object.International', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  8, NULL, 0, 0, NULL, NULL, N'default.html?helpcontent=mergedProjects/sl_custvend/fields/i/international_ship_via_codes.htm', -1, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, N'ListYesNo', 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sInternational')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'ModeOfTransportEdit', -1, 
  8, 27, CAST('5.5300000000000002' AS float), CAST('21.142857142857142' AS float), CAST('1.2941176470588236' AS float), CAST('2' AS float), CAST('18' AS float), N'C(TransportStatic)', 
  NULL, 
  NULL, 0, N'object.Transport', 
  1, NULL, NULL, NULL, NULL, NULL, 
  N'INLINE ENTRIES(F\Entrega a Cliente,C\Retira en Sucursal) DISPLAY(2) VALUE(1)', 
  513, NULL, 0, 0, NULL, NULL, N'default.html?helpcontent=mergedProjects/sl_custvend/fields/m/mode_of_transport_ship_via_codes.htm', -1, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, N'Transport', 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'C(TransportStatic)')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'ShipCodeEdit', -1, 
  3, 1, CAST('1.5966666666666667' AS float), CAST('14' AS float), CAST('1.3' AS float), CAST('2' AS float), CAST('6' AS float), N'C(ShipCodeStatic)', 
  NULL, 
  NULL, 0, N'object.ShipCode', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  1, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, N'ShipCodeBase', 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'C(ShipCodeStatic)')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'ShipCodeGridCol', -1, 
  1, 15, CAST('0' AS float), CAST('0' AS float), CAST('15.199999999999999' AS float), CAST('2' AS float), CAST('8' AS float), NULL, 
  NULL, 
  N'FormCollectionGrid', 0, N'object.ShipCode', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 0, NULL, NULL, N'default.html?helpcontent=mergedProjects/sl_custvend/fields/c/code_ship_via_codes.htm', -1, N'StdDefault', 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, N'ShipCodeBase', 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sCode')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'ShipCodeStatic', -1, 
  2, 0, CAST('1.8966666666666667' AS float), CAST('1.5714285714285714' AS float), CAST('1' AS float), CAST('2' AS float), CAST('11.714285714285714' AS float), NULL, 
  NULL, 
  NULL, 0, NULL, 
  0, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  1, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl) JUSTIFY(R)', 
  NULL, N'sCode')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'TransportGridCol', -1, 
  3, 15, CAST('0' AS float), CAST('8.1428571428571424' AS float), CAST('15.199999999999999' AS float), CAST('2' AS float), CAST('8' AS float), NULL, 
  NULL, 
  N'FormCollectionGrid', 2, N'object.Transport', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 0, NULL, NULL, N'default.html?helpcontent=mergedProjects/sl_custvend/fields/m/mode_of_transport_ship_via_codes.htm', -1, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, N'Transport', 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sModeofTransport')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'TransportStatic', -1, 
  7, 0, CAST('5.8300000000000001' AS float), CAST('3.7142857142857126' AS float), CAST('1' AS float), CAST('2' AS float), CAST('16.714285714285715' AS float), NULL, 
  NULL, 
  NULL, 0, NULL, 
  0, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  1, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl) JUSTIFY(R)', 
  NULL, N'sModeofTransport')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'WhereUsed', -1, 
  4, 10, CAST('0' AS float), CAST('0' AS float), CAST('0' AS float), CAST('0' AS float), CAST('0' AS float), N'sWhereUsed', 
  NULL, 
  NULL, 3, NULL, 
  0, N'LaunchWhereUsed', NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 0, NULL, NULL, NULL, -1, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sWhereUsed')
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'GoToMaintenanceFolder', 0, 41, N'MASTER/xModules/xCodes', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'GoToQueriesFolder', 0, 41, N'MASTER/xModules/xCodes/xQueries', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'LaunchWhereUsed', 0, 6, N'WhereUsedShipViaCodes( LINKBY(ShipCode=ShipCode) )', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'StdFormCopy', 0, 21, N'StdFormPerformValidations(  )', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'StdFormCopyCompleted', 0, 8, N'CopyCompletedMarkComponentsValid()', NULL, NULL, NULL )
INSERT INTO Variables ( [FormID], [Name], [ScopeType], [ScopeName], [Value], [Value2], [Value3], [LockedBy], [Description] ) 
VALUES (@FormID, N'InitialCommand', 1, N'[NULL]', N'Refresh', NULL, NULL, NULL, NULL)
DELETE FROM ActiveXScriptLines WHERE ScriptName = N'ZPV_ShipCodes' AND [ScopeType] = 1
DELETE FROM ActiveXScripts WHERE Name = N'ZPV_ShipCodes' AND [ScopeType] = 1
INSERT INTO ActiveXScripts ([Name], [ScopeType], [ScopeName], [LockedBy], [Language]) VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', NULL, N'Visual Basic')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 0, N'Option Explicit On')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 1, N'Option Strict On')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 2, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 3, N'Imports System')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 4, N'Imports Microsoft.VisualBasic')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 5, N'Imports Mongoose.IDO.Protocol')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 6, N'Imports Mongoose.Scripting')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 7, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 8, N'Namespace SyteLine.FormScripts')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 9, N'    Public Class ZPV_ShipCodes')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 10, N'        Inherits FormScript')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 11, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 12, N'        Sub MessageForDuplicateTransportCode()')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 13, N'            Dim idx As Long')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 14, N'            ''Loop through each record in the current collection')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 15, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 16, N'            For idx = 0 To ThisForm.PrimaryIDOCollection.GetNumEntries - 1')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 17, N'                If Not (ThisForm.PrimaryIDOCollection.GetCurrentObjectIndex = idx) Then')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 18, N'                    If (ThisForm.PrimaryIDOCollection.GetObjectProperty("Transport", CInt(idx)) <> "") Then')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 19, N'                        If ThisForm.PrimaryIDOCollection.GetObjectProperty("Transport", CInt(idx)) = ThisForm.Components("TransportGridCol").Text Then')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 20, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 21, N'                            ThisForm.CallGlobalScript( _')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 22, N'                                       "MsgApp", _')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 23, N'                                       "Clear", _')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 24, N'                                       "Prompt", _')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 25, N'                                       "SuccessFailure", _')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 26, N'                                       "mW=MayNotBeDuplicate", _')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 27, N'                                       "@sModeofTransport", _')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 28, N'                                       "", "", "", "", "", "", "", "", "", "", "", "", "", "", "")')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 29, N'                            Exit For')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 30, N'                        End If')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 31, N'                    End If')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 32, N'                End If')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 33, N'            Next')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 34, N'        End Sub')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 35, N'    End Class')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_ShipCodes', 1, N'[NULL]', 36, N'End Namespace')
