-------------------------------------------------------------------------------
-- SQL Script generated by FormSync 9.1.0.21 As of 26/04/2015 18:50
-- Source Configuration: ELDORADO_Forms
-------------------------------------------------------------------------------
DECLARE @FormID int
SET @FormID = NULL
SELECT @FormID = Forms.ID FROM Forms WHERE [Name] = N'ZPV_CustomerOrdersB2B' AND [ScopeType] = 1
IF @FormID IS NOT NULL
BEGIN
   DELETE FROM Forms WHERE ID = @FormID
   DELETE FROM FormEventHandlers WHERE FormID = @FormID
   DELETE FROM FormComponents WHERE FormID = @FormID
   DELETE FROM ActiveXComponentProperties WHERE FormID = @FormID
   DELETE FROM Variables WHERE FormID = @FormID
   DELETE FROM FormComponentDragDropEvents WHERE FormID = @FormID
   DELETE FROM DerivedFormOverrides WHERE FormID = @FormID
END
INSERT INTO [Forms] (
  [ScopeType], [ScopeName], [Component], [Name], [SubComponent], [Type], [Caption], 
  [PrimaryDataSource], 
  [StandardOperations], [TopPos], [LeftPos], [Height], [Width], [IconFileName], [HelpFileName], [HelpContextID], [Flags], [LockedBy], 
  [FilterFormSpec], [PaneZeroSize], [Description], [MasterDeviceID], [BaseFormName] ) 
VALUES ( 
  1, N'[NULL]', NULL, N'ZPV_CustomerOrdersB2B', NULL, 1, N'Importacion Masiva de Pedidos', 
  N'V(fds_DataSource)', 
  673, CAST('0' AS float), CAST('0' AS float), CAST('40' AS float), CAST('120' AS float), NULL, NULL, -1, 8, N'sa', 
  NULL, N'0', NULL, 0, NULL)
SELECT @FormID = Forms.ID FROM Forms WHERE [Name] = N'ZPV_CustomerOrdersB2B' AND [ScopeType] = 1
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'button1', -1, 
  0, 8, CAST('36.352941176470587' AS float), CAST('50.375' AS float), CAST('1.3529411764705883' AS float), CAST('0' AS float), CAST('15.25' AS float), N'Ordenar Pedidos', 
  NULL, 
  NULL, 0, NULL, 
  0, N'OrdenarPedidos', NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'Ordenar Pedidos')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'button2', -1, 
  0, 8, CAST('38.117647058823529' AS float), CAST('50.375' AS float), CAST('1.3529411764705883' AS float), CAST('0' AS float), CAST('15.25' AS float), N'Eliminar Pedidos', 
  NULL, 
  NULL, 0, NULL, 
  0, N'EliminarPedidos', NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'Eliminar Pedidos')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'CoLineGridCol', -1, 
  0, 15, CAST('0' AS float), CAST('0' AS float), CAST('5.882352941176471' AS float), CAST('0' AS float), CAST('6' AS float), N'sLine', 
  NULL, 
  N'CustomerOrderLinesGrid', 0, N'object.SLCoBlns.CoLine', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, N'CoLineBase', 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sLine')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'comboBox1', -1, 
  0, 27, CAST('2.5294117647058822' AS float), CAST('12.625' AS float), CAST('1.2352941176470589' AS float), CAST('0' AS float), CAST('11.25' AS float), NULL, 
  NULL, 
  NULL, 0, N'variables.vPOS(CLEARONREFRESH())', 
  6, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  512, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', N'ZPV_POS()', NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, NULL)
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'CoNumGridCol', -1, 
  0, 15, CAST('0' AS float), CAST('0' AS float), CAST('5.882352941176471' AS float), CAST('0' AS float), CAST('10' AS float), N'sCoNum', 
  NULL, 
  N'CustomerOrderGrid', 1, N'object.CoNum', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 1, 0, NULL, NULL, NULL, 0, N'StdDetailsAddFind', 
  NULL, N'CustomerOrdersQuery.CoNum', N'ZPV_CustomerOrdersPOS( PROPERTY(CoNum) )', 
  N'0', N'CoNumVar()', NULL, NULL, N'CoNumBase', 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sCoNum')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'CustNumEdit', -1, 
  0, 27, CAST('1' AS float), CAST('12.625' AS float), CAST('1.3' AS float), CAST('0' AS float), CAST('11.125' AS float), N'Cliente Grandes Cadenas', 
  NULL, 
  NULL, 0, N'variables.vCustNum(CLEARONREFRESH())', 
  6, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  512, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', N'CustomerZeroVar(vName)', NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'Cliente Grandes Cadenas')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'CustomerOrderGrid', -1, 
  0, 14, CAST('4.9411764705882355' AS float), CAST('3.25' AS float), CAST('18.117647058823529' AS float), CAST('0' AS float), CAST('112.375' AS float), NULL, 
  NULL, 
  NULL, 0, N'objects', 
  3, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, NULL)
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'CustomerOrderLinesGrid', -1, 
  0, 14, CAST('23.647058823529413' AS float), CAST('3.25' AS float), CAST('8.8235294117647065' AS float), CAST('0' AS float), CAST('112.25' AS float), NULL, 
  NULL, 
  NULL, 0, N'V(cds_DataSourceCustomerOrderLinesGrid)', 
  4, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, NULL)
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'DescriptionGridCol', -1, 
  0, 15, CAST('0' AS float), CAST('0' AS float), CAST('5.882352941176471' AS float), CAST('0' AS float), CAST('40' AS float), N'sDescription', 
  NULL, 
  N'CustomerOrderLinesGrid', 3, N'object.SLCoBlns.Description', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, N'ItemDescription', 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sDescription')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'edit1', -1, 
  0, 1, CAST('37.647058823529413' AS float), CAST('6' AS float), CAST('1.1764705882352942' AS float), CAST('0' AS float), CAST('12.5' AS float), NULL, 
  NULL, 
  NULL, 0, N'variables.vCustType', 
  6, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 1, 1, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, NULL)
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'F12GridCol', -1, 
  0, 15, CAST('0' AS float), CAST('0' AS float), CAST('5.882352941176471' AS float), CAST('0' AS float), CAST('13' AS float), N'Nro F12', 
  NULL, 
  N'CustomerOrderGrid', 0, N'object.ZpvF12', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  N'DATATYPE(NUMSORTCHAR)', N'AUTOIME(NoControl)', 
  NULL, N'Nro F12')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'FilePathEdit', -1, 
  0, 1, CAST('1' AS float), CAST('68' AS float), CAST('1.3' AS float), CAST('0' AS float), CAST('44.75' AS float), NULL, 
  NULL, 
  NULL, 0, N'variables.vFilePath(CLEARONREFRESH())', 
  6, NULL, N'CheckAndOpenFile', NULL, NULL, NULL, 
  NULL, 
  512, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, NULL)
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'FilePathEdit1', -1, 
  0, 1, CAST('33.117647058823529' AS float), CAST('33.875' AS float), CAST('1.3' AS float), CAST('0' AS float), CAST('44.75' AS float), N'FilePathEdit1', 
  NULL, 
  NULL, 0, N'variables.vFilePathProm(CLEARONREFRESH())', 
  6, NULL, N'CheckAndOpenFileProm', NULL, NULL, NULL, 
  NULL, 
  512, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'FilePathEdit1')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'groupBox1', -1, 
  0, 6, CAST('32.308823529411768' AS float), CAST('3.125' AS float), CAST('2.5882352941176472' AS float), CAST('0' AS float), CAST('112.5' AS float), NULL, 
  NULL, 
  NULL, 0, NULL, 
  0, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, NULL)
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'ItemGridCol', -1, 
  0, 15, CAST('0' AS float), CAST('0' AS float), CAST('5.882352941176471' AS float), CAST('0' AS float), CAST('20' AS float), N'sItem', 
  NULL, 
  N'CustomerOrderLinesGrid', 1, N'object.SLCoBlns.Item', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', N'ItemVar()', NULL, NULL, N'Item', 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sItem')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'NameEdit', -1, 
  0, 1, CAST('1' AS float), CAST('24' AS float), CAST('1.3' AS float), CAST('0' AS float), CAST('33.25' AS float), NULL, 
  NULL, 
  NULL, 0, N'variables.vName(CLEARONREFRESH())', 
  6, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, NULL)
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'OrderDateGridCol', -1, 
  0, 15, CAST('0' AS float), CAST('0' AS float), CAST('5.882352941176471' AS float), CAST('0' AS float), CAST('12' AS float), N'sOrderDate', 
  NULL, 
  N'CustomerOrderGrid', 2, N'object.OrderDate', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', N'DateVar()', NULL, NULL, N'Date', 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sOrderDate')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'PriceGridCol', -1, 
  0, 15, CAST('0' AS float), CAST('0' AS float), CAST('5.882352941176471' AS float), CAST('0' AS float), CAST('15' AS float), N'sTotalPrice', 
  NULL, 
  N'CustomerOrderGrid', 5, N'object.ZpvTotalCOAmt', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', N'AmountVar()', NULL, NULL, N'Amount', 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sTotalPrice')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'QtyGridCol', -1, 
  0, 15, CAST('0' AS float), CAST('0' AS float), CAST('5.882352941176471' AS float), CAST('0' AS float), CAST('12' AS float), N'sQtyOrdered', 
  NULL, 
  N'CustomerOrderLinesGrid', 4, N'object.SLCoBlns.BlanketQty', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', N'QtyUnitVar()', NULL, NULL, N'QtyTotl', 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sQtyOrdered')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'SKUGridCol', -1, 
  0, 15, CAST('0' AS float), CAST('0' AS float), CAST('5.882352941176471' AS float), CAST('0' AS float), CAST('15' AS float), N'SKU', 
  NULL, 
  N'CustomerOrderLinesGrid', 2, NULL, 
  0, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'SKU')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'static1', -1, 
  0, 0, CAST('1.1764705882352942' AS float), CAST('3.75' AS float), CAST('0.76470588235294112' AS float), CAST('0' AS float), CAST('8.125' AS float), N'sCustNum', 
  NULL, 
  NULL, 0, NULL, 
  0, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl) JUSTIFY(R)', 
  NULL, N'sCustNum')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'static2', -1, 
  0, 0, CAST('1.1176470588235294' AS float), CAST('57.875' AS float), CAST('0.76470588235294112' AS float), CAST('0' AS float), CAST('9.625' AS float), N'Archivo B2B', 
  NULL, 
  NULL, 0, NULL, 
  0, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl) JUSTIFY(R)', 
  NULL, N'Archivo B2B')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'static3', -1, 
  0, 0, CAST('2.7647058823529411' AS float), CAST('0.375' AS float), CAST('0.76470588235294112' AS float), CAST('0' AS float), CAST('11.375' AS float), N'Punto de Venta', 
  NULL, 
  NULL, 0, NULL, 
  0, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl) JUSTIFY(R)', 
  NULL, N'Punto de Venta')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'static5', -1, 
  0, 0, CAST('33.235294117647058' AS float), CAST('13.75' AS float), CAST('0.76470588235294112' AS float), CAST('0' AS float), CAST('19.625' AS float), N'Archivo B2B Promotor', 
  NULL, 
  NULL, 0, NULL, 
  0, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl) JUSTIFY(R)', 
  NULL, N'Archivo B2B Promotor')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'TotalPriceGridCol', -1, 
  0, 15, CAST('0' AS float), CAST('0' AS float), CAST('5.882352941176471' AS float), CAST('0' AS float), CAST('15' AS float), N'sTotalPrice', 
  NULL, 
  N'CustomerOrderLinesGrid', 5, N'object.SLCoBlns.ZpvTotal', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', N'AmountVar()', NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sTotalPrice')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'UsernameEdit', -1, 
  0, 1, CAST('2.4117647058823528' AS float), CAST('94.75' AS float), CAST('1.1764705882352942' AS float), CAST('0' AS float), CAST('17.625' AS float), NULL, 
  NULL, 
  NULL, 0, N'variables.vUsername(INITIALVALUE(USERNAME()))', 
  6, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, NULL)
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'ZpvBillNameGridCol', -1, 
  0, 15, CAST('0' AS float), CAST('0' AS float), CAST('5.882352941176471' AS float), CAST('0' AS float), CAST('40' AS float), N'sName', 
  NULL, 
  N'CustomerOrderGrid', 4, N'object.ZpvBillFiscalName', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sName')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'ZpvStatGridCol', -1, 
  0, 15, CAST('0' AS float), CAST('0' AS float), CAST('5.882352941176471' AS float), CAST('0' AS float), CAST('12' AS float), N'sStat', 
  NULL, 
  N'CustomerOrderGrid', 3, N'object.ZpvStat', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', N'ZPV_CoStats()', NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sStat')
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'CheckAndOpenFile', 0, 35, N'CheckAndOpenFile()', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'CheckAndOpenFileProm', 0, 35, N'CheckAndOpenFileProm()', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'EliminarPedidos', 0, 0, N'ZPV_SLCos.ZPV_RetailCO_EliminarSp( PARMS(VAR V(vCustNum), MESSAGE) ERRORMESSAGE(mBackendMessage) SUCCESSMESSAGE(mBackendMessage) )', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'EliminarPedidos', 1, 28, N'object', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'OpenFile', 0, 35, N'OpenGetFile() DISABLED()', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'OpenFile', 1, 0, N'ZPV_SLCos.ZPV_CLM_RetailCOSp( PARMS(VAR V(vFilePath), VAR V(vCustNum), VAR V(vUsername), VAR , VAR V(vPOS), MESSAGE) ERRORMESSAGE(mBackendMessage) SUCCESSMESSAGE(mBackendMessage) )', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'OpenFile', 2, 28, N'object', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'OpenFileProm', 0, 35, N'OpenGetFileProm() DISABLED()', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'OpenFileProm', 1, 0, N'ZPV_SLCos.ZPV_CLM_RetailCOCustomerDataSp( PARMS(VAR V(vFilePathProm), VAR V(vCustNum), MESSAGE) ERRORMESSAGE(mBackendMessage) SUCCESSMESSAGE(mBackendMessage) )', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'OpenFileProm', 2, 28, N'object', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'OrdenarPedidos', 0, 0, N'ZPV_SLCos.ZPV_RetailCO_OrderedSp( PARMS(VAR V(vCustNum), MESSAGE) ERRORMESSAGE(mBackendMessage) SUCCESSMESSAGE(mBackendMessage) )', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'OrdenarPedidos', 1, 28, N'object', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'StdFormPredisplay', 0, 28, N'object', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'StdFormPredisplay', 1, 0, N'ZPV_SLCos.ZPV_GetGenericCustTypeSp( PARMS(RVAR, RVAR V(vCustType), RVAR , MESSAGE) ERRORMESSAGE(mBackendMessage) SUCCESSMESSAGE(mBackendMessage) )', NULL, NULL, NULL )
INSERT INTO Variables ( [FormID], [Name], [ScopeType], [ScopeName], [Value], [Value2], [Value3], [LockedBy], [Description] ) 
VALUES (@FormID, N'cds_DataSourceCustomerOrderLinesGrid', 1, N'[NULL]', N'object.SLCoBlns( CA(IVR) LINKBY(CoNum=CoNum) )', NULL, NULL, NULL, NULL)
INSERT INTO Variables ( [FormID], [Name], [ScopeType], [ScopeName], [Value], [Value2], [Value3], [LockedBy], [Description] ) 
VALUES (@FormID, N'fds_DataSource', 1, N'[NULL]', N'ZPV_SLCos( OBJNAME(oCos) FILTERPERM((ZpvStat = ''E00'' or ZpvStat = ''R00'') and CustNum = FV(vCustNum) and ZpvF12 IS NOT NULL) )', NULL, NULL, NULL, NULL)
INSERT INTO Variables ( [FormID], [Name], [ScopeType], [ScopeName], [Value], [Value2], [Value3], [LockedBy], [Description] ) 
VALUES (@FormID, N'vCustNum', 1, N'[NULL]', N'~LIT~(SVPN)', NULL, NULL, NULL, NULL)
INSERT INTO Variables ( [FormID], [Name], [ScopeType], [ScopeName], [Value], [Value2], [Value3], [LockedBy], [Description] ) 
VALUES (@FormID, N'vCustType', 1, N'[NULL]', N'~LIT~(01)', NULL, NULL, NULL, NULL)
INSERT INTO Variables ( [FormID], [Name], [ScopeType], [ScopeName], [Value], [Value2], [Value3], [LockedBy], [Description] ) 
VALUES (@FormID, N'vFilePath', 1, N'[NULL]', N'~LIT~(B2B.xlsx)', NULL, NULL, NULL, NULL)
INSERT INTO Variables ( [FormID], [Name], [ScopeType], [ScopeName], [Value], [Value2], [Value3], [LockedBy], [Description] ) 
VALUES (@FormID, N'vFilePathProm', 1, N'[NULL]', N'~LIT~(C:\B2BProm.xlsx)', NULL, NULL, NULL, NULL)
INSERT INTO Variables ( [FormID], [Name], [ScopeType], [ScopeName], [Value], [Value2], [Value3], [LockedBy], [Description] ) 
VALUES (@FormID, N'vName', 1, N'[NULL]', N'~LIT~(SODIMAC COLOMBIA S A)', NULL, NULL, NULL, NULL)
INSERT INTO Variables ( [FormID], [Name], [ScopeType], [ScopeName], [Value], [Value2], [Value3], [LockedBy], [Description] ) 
VALUES (@FormID, N'vPOS', 1, N'[NULL]', N'~LIT~(001)', NULL, NULL, NULL, NULL)
INSERT INTO Variables ( [FormID], [Name], [ScopeType], [ScopeName], [Value], [Value2], [Value3], [LockedBy], [Description] ) 
VALUES (@FormID, N'vSlsman', 1, N'[NULL]', N'~LIT~(10123224)', NULL, NULL, NULL, NULL)
INSERT INTO Variables ( [FormID], [Name], [ScopeType], [ScopeName], [Value], [Value2], [Value3], [LockedBy], [Description] ) 
VALUES (@FormID, N'vUsername', 1, N'[NULL]', N'~LIT~(sa)', NULL, NULL, NULL, NULL)
DELETE FROM ActiveXScriptLines WHERE ScriptName = N'ZPV_CustomerOrdersB2B' AND [ScopeType] = 1
DELETE FROM ActiveXScripts WHERE Name = N'ZPV_CustomerOrdersB2B' AND [ScopeType] = 1
INSERT INTO ActiveXScripts ([Name], [ScopeType], [ScopeName], [LockedBy], [Language]) VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', NULL, N'Visual Basic')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 0, N'Option Explicit On')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 1, N'Option Strict On')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 2, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 3, N'Imports System')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 4, N'Imports Microsoft.VisualBasic')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 5, N'Imports Mongoose.IDO.Protocol')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 6, N'Imports Mongoose.Scripting')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 7, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 8, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 9, N'Namespace Mongoose.FormScripts')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 10, N'Public Class ZPV_CustomerOrdersB2B')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 11, N'Inherits FormScript')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 12, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 13, N'        Sub OpenGetFile()')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 14, N'            Dim bDialogResponse As Boolean = False')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 15, N'            Dim sNoteContent As String = String.Empty')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 16, N'            Dim sWarningMessage As String = String.Empty')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 17, N'            Dim wsUserResponse As wsMsgBoxResult = wsMsgBoxResult.wsOK')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 18, N'            Dim FileName As String = String.Empty')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 19, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 20, N'            If wsUserResponse = wsMsgBoxResult.wsOK Then')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 21, N'                If Application.Platform = "WIN" Then')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 22, N'                    bDialogResponse = Application.ShowOpenFileDialog(FileName, Application.GetStringValue("sAttachFile"), "All Files (*.*)|*.*")')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 23, N'                    If bDialogResponse Then')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 24, N'                        ThisForm.Variables("vFilePath").Value = FileName')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 25, N'                    End If')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 26, N'                End If')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 27, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 28, N'            End If')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 29, N'        End Sub')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 30, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 31, N'        Sub OpenGetFileProm()')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 32, N'            Dim bDialogResponse As Boolean = False')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 33, N'            Dim sNoteContent As String = String.Empty')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 34, N'            Dim sWarningMessage As String = String.Empty')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 35, N'            Dim wsUserResponse As wsMsgBoxResult = wsMsgBoxResult.wsOK')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 36, N'            Dim FileName As String = String.Empty')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 37, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 38, N'            If wsUserResponse = wsMsgBoxResult.wsOK Then')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 39, N'                If Application.Platform = "WIN" Then')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 40, N'                    bDialogResponse = Application.ShowOpenFileDialog(FileName, Application.GetStringValue("sAttachFile"), "All Files (*.*)|*.*")')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 41, N'                    If bDialogResponse Then')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 42, N'                        ThisForm.Variables("vFilePathProm").Value = FileName')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 43, N'                    End If')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 44, N'                End If')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 45, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 46, N'            End If')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 47, N'        End Sub')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 48, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 49, N'        Sub CheckAndOpenFile()')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 50, N'            If ThisForm.Variables("vCustNum").Value <> "" And')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 51, N'                ThisForm.Variables("vPOS").Value <> "" And')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 52, N'                ThisForm.Variables("vSlsman").Value <> "" Then')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 53, N'                ThisForm.GenerateEvent("OpenFile")')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 54, N'            Else')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 55, N'                Application.ShowMessage("Debe especificar Cliente, Punto de Venta y Vendedor", MsgBoxStyle.Information, "Punto de Venta")')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 56, N'                ThisForm.SetFocus("CustNumEdit")')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 57, N'            End If')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 58, N'        End Sub')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 59, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 60, N'        Sub CheckAndOpenFileProm()')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 61, N'            If ThisForm.Variables("vCustNum").Value <> "" And')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 62, N'                ThisForm.Variables("vPOS").Value <> "" And')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 63, N'                ThisForm.Variables("vSlsman").Value <> "" Then')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 64, N'                ThisForm.GenerateEvent("OpenFileProm")')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 65, N'            Else')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 66, N'                Application.ShowMessage("Debe especificar Cliente, Punto de Venta y Vendedor", MsgBoxStyle.Information, "Punto de Venta")')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 67, N'                ThisForm.SetFocus("CustNumEdit")')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 68, N'            End If')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 69, N'        End Sub')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 70, N'End Class')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZPV_CustomerOrdersB2B', 1, N'[NULL]', 71, N'End Namespace')
