-------------------------------------------------------------------------------
-- SQL Script generated by FormSync 9.1.0.21 As of 26/04/2015 18:51
-- Source Configuration: ELDORADO_Forms
-------------------------------------------------------------------------------
DECLARE @FormID int
DELETE FROM [Validators] WHERE [Name] = N'ZRT_POSPayCode' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 

INSERT INTO [Validators] ([Name], [ScopeType], [ScopeName], [Type], [Parms], [Parms2], [Parms3], [ErrorMsg], [LockedBy], [Description] ) 
VALUES (N'ZRT_POSPayCode', 1, N'[NULL]', 9, N'ZRT_POSMPayTypes( PROPERTY(PosmPayType) SETP(%1=Logifld, %2=BankCode,%3=ZlaBankType)SETV(%4=TransType) )', NULL, NULL, N'mIsNotAValid', NULL, NULL) 
