-------------------------------------------------------------------------------
-- SQL Script generated by FormSync 9.1.0.21 As of 26/04/2015 18:51
-- Source Configuration: ELDORADO_Forms
-------------------------------------------------------------------------------
DECLARE @FormID int
DELETE FROM [Validators] WHERE [Name] = N'ZRT_ValidateTerms' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 

INSERT INTO [Validators] ([Name], [ScopeType], [ScopeName], [Type], [Parms], [Parms2], [Parms3], [ErrorMsg], [LockedBy], [Description] ) 
VALUES (N'ZRT_ValidateTerms', 1, N'[NULL]', 7, N'ZRT_CoPayments.ZRT_ValidatePayTypeSp( PARMS(VAR P(CoNum), VAR P(ZRT_CoPayments.pay_type), VAR P(ZRT_CoPayments.cc_bank), RVAR V(NoPay), RVAR V(NoPayMsg)) OIO() )', NULL, NULL, N'mBackEndMessage', NULL, NULL) 
