-------------------------------------------------------------------------------
-- SQL Script generated by FormSync 9.1.0.21 As of 26/04/2015 18:51
-- Source Configuration: ELDORADO_Forms
-------------------------------------------------------------------------------
DECLARE @FormID int
DELETE FROM [Validators] WHERE [Name] = N'ZPV_ShipCode' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 

INSERT INTO [Validators] ([Name], [ScopeType], [ScopeName], [Type], [Parms], [Parms2], [Parms3], [ErrorMsg], [LockedBy], [Description] ) 
VALUES (N'ZPV_ShipCode', 1, N'[NULL]', 9, N'SLShipcodes( PROPERTY(ShipCode) SETP(%1=Description,%2=Transport)SETV(%3=Transport) )', NULL, NULL, N'mIsNotAValid', NULL, NULL) 
