/****** Object:  StoredProcedure [dbo].[ZPV_ValidatePayTypeSp]    Script Date: 10/29/2014 12:16:03 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ZPV_ValidatePayTypeSp]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[ZPV_ValidatePayTypeSp]
GO

/****** Object:  StoredProcedure [dbo].[ZPV_ValidatePayTypeSp]    Script Date: 10/29/2014 12:16:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[ZPV_ValidatePayTypeSp] (
	@CoNum		CoNumType,
	@PosmPayType	PosmPayTypeType,
	@BankCode	BankCodeType,
	@NoPayment	int output,
	@Infobar	InfobarType   OUTPUT
)
AS

   -- Check for existence of Generic External Touch Point routine (this section was generated by SpETPCodeSp and inserted by CallETPs.exe):
   IF OBJECT_ID(N'dbo.EXTGEN_ZPV_ValidatePayTypeSp') IS NOT NULL
   BEGIN
      DECLARE @EXTGEN_SpName sysname
      SET @EXTGEN_SpName = N'dbo.EXTGEN_ZPV_ValidatePayTypeSp'
      -- Invoke the ETP routine, passing in (and out) this routine's parameters:
      DECLARE @EXTGEN_Severity int
      EXEC @EXTGEN_Severity = @EXTGEN_SpName
         @CoNum
         , @PosmPayType
         , @BankCode
         , @NoPayment OUTPUT
         , @Infobar OUTPUT
 
      -- ETP routine can RETURN 1 to signal that the remainder of this standard routine should now proceed:
      IF @EXTGEN_Severity <> 1
         RETURN @EXTGEN_Severity
   END
   -- End of Generic External Touch Point code.

DECLARE
  @Severity             INT
declare
	@TermsCode	TermsCodeType,
	@TermsDisc	AmountType,
	@PayDiscTerms	int,
	@OrderDate	DateType,
	@StartDate	DateType,
	@EndDate	DateType

SET @Severity = 0
SET @Infobar  = NULL

BEGIN
	select
		@TermsCode = co_mst.terms_code,
		@OrderDate = co_mst.order_date	
	from co_mst
	where
		co_mst.co_num = @CoNum
		
	select 
		@TermsDisc = terms.disc_pct
	from terms_mst terms
	where
		terms.terms_code = @TermsCode
		
	select 
		@PayDiscTerms	= bank.term_disc,
		@StartDate		= bank.from_date,
		@EndDate		= bank.to_date
	from zpv_bank_ptype bank
	where
		bank.posm_pay_type = @PosmPayType and
		bank.bank_id = @BankCode
			
	select
		@CoNum,
		@PosmPayType,
		@TermsCode,
		@TermsDisc,
		@PayDiscTerms

	if @PayDiscTerms = 0
	begin
		if @TermsDisc > 0 and @OrderDate between @StartDate and @EndDate
		begin
			set @Infobar = 'El tipo de pago no acepta descuentos en cabecera'
			set @NoPayment = 1
		end
		else
		begin
			set @Infobar = ''
			set @NoPayment = 0
		end
	end
	else
	begin
		set @Infobar = ''
		set @NoPayment = 0
	end
end

return @severity





GO

