/****** Object:  StoredProcedure [dbo].[ZPV_DrawerTransactionSp]    Script Date: 10/29/2014 12:15:16 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ZPV_DrawerTransactionSp]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[ZPV_DrawerTransactionSp]
GO

/****** Object:  StoredProcedure [dbo].[ZPV_DrawerTransactionSp]    Script Date: 10/29/2014 12:15:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


/* $Header: /ApplicationDB/Stored Procedures/ARPaymentPostingSp.sp 73    4/11/14 4:02a Ychen1 $ */
/*
***************************************************************
*                                                             *
*                           NOTICE                            *
*                                                             *
*   THIS SOFTWARE IS THE PROPERTY OF AND CONTAINS             *
*   CONFIDENTIAL INFORMATION OF INFOR AND/OR ITS AFFILIATES   *
*   OR SUBSIDIARIES AND SHALL NOT BE DISCLOSED WITHOUT PRIOR  *
*   WRITTEN PERMISSION. LICENSED CUSTOMERS MAY COPY AND       *
*   ADAPT THIS SOFTWARE FOR THEIR OWN USE IN ACCORDANCE WITH  *
*   THE TERMS OF THEIR SOFTWARE LICENSE AGREEMENT.            *
*   ALL OTHER RIGHTS RESERVED.                                *
*                                                             *
*   (c) COPYRIGHT 2010 INFOR.  ALL RIGHTS RESERVED.           *
*   THE WORD AND DESIGN MARKS SET FORTH HEREIN ARE            *
*   TRADEMARKS AND/OR REGISTERED TRADEMARKS OF INFOR          *
*   AND/OR ITS AFFILIATES AND SUBSIDIARIES. ALL RIGHTS        *
*   RESERVED.  ALL OTHER TRADEMARKS LISTED HEREIN ARE         *
*   THE PROPERTY OF THEIR RESPECTIVE OWNERS.                  *
*                                                             *
***************************************************************
*/

CREATE PROCEDURE [dbo].[ZPV_DrawerTransactionSp] (
@PCoNum				CoNumType
, @PDrawer			varchar(15)
, @Infobar             Infobar        OUTPUT
) AS

   -- Check for existence of Generic External Touch Point routine (this section was generated by SpETPCodeSp and inserted by CallETPs.exe):
   IF OBJECT_ID(N'dbo.EXTGEN_ZPV_DrawerTransactionSp') IS NOT NULL
   BEGIN
      DECLARE @EXTGEN_SpName sysname
      SET @EXTGEN_SpName = N'dbo.EXTGEN_ZPV_DrawerTransactionSp'
      -- Invoke the ETP routine, passing in (and out) this routine's parameters:
      DECLARE @EXTGEN_Severity int
      EXEC @EXTGEN_Severity = @EXTGEN_SpName
           @PCoNum
         , @PDrawer  
         , @Infobar OUTPUT
 
      -- ETP routine can RETURN 1 to signal that the remainder of this standard routine should now proceed:
      IF @EXTGEN_Severity <> 1
         RETURN @EXTGEN_Severity
   END
   -- End of Generic External Touch Point code.
 
DECLARE
  @Severity             INT

SET @Severity = 0
SET @Infobar  = NULL

--ZPV_DRAWER_TRANS
DECLARE
  @ZpvDrwTransNum		MatlTransNumType
, @ZpvDrwType			varchar(1)
, @ZpvDrwReliefNum		MatlTransNumType
, @ZpvDrwTransDate		DateType
, @ZpvDrwPacket			varchar(20)
, @ZpvDrwDrawer			varchar(15)
, @ZpvDrwGlbankRowpointer	RowpointerType
, @ZpvDrwCopayRowpointer	RowpointerType
, @ZpvDrwAmount			AmountType
, @ZpvDrwCurrCode		CurrCodeType
, @ZpvDrwExchRate		ExchRateType
, @ZpvDrwForAmount		AmountType
, @ZpvDrwApplyDate		DateType
, @ZpvDrwarTypeId		ZlaArTypeIdType
, @ZpvDrwCoNum			CoNumType

DECLARE
  @ZpvCoPaymentPaySeq	int
, @ZpvCoPaymentPayType	varchar(10)
, @ZpvCoPaymentAmount	AmountType
, @ZpvCoPaymentRowPointer	RowpointerType
, @ZpvCoPaymentCurrCode	CurrCodeType
, @ZpvCoPaymentBankCode	BankCodeType
, @ZpvCoPaymentCheckNum	ARCheckNumType
, @ZpvCoPaymentExchRate ExchRateType
, @ZpvCoPaymentForAmount	AmountType
, @ZpvCoPaymentDrawer	varchar(15)
, @ZpvCoPaymentArPayId	ZlaArPayIdType


DECLARE PaymentCur CURSOR FOR
SELECT
	pay.pay_seq,
	pay.pay_type,
	pay.amount,
	pay.RowPointer,
	pay.curr_code,
	pay.bank_code,
	pay.exch_rate,
	pay.for_amount,
	pay.drawer,
	pay.ar_pay_id,
	pay.check_num
FROM zpv_co_payment pay
WHERE
	pay.co_num	= @PCoNum
OPEN PaymentCur
FETCH NEXT FROM PaymentCur
INTO
	@ZpvCoPaymentPaySeq	
	, @ZpvCoPaymentPayType
	, @ZpvCoPaymentAmount
	, @ZpvCoPaymentRowPointer
	, @ZpvCoPaymentCurrCode	
	, @ZpvCoPaymentBankCode	
	, @ZpvCoPaymentExchRate 
	, @ZpvCoPaymentForAmount
	, @ZpvCoPaymentDrawer	
	, @ZpvCoPaymentArPayId	
	, @ZpvCoPaymentCheckNum

WHILE @@FETCH_STATUS = 0
BEGIN
	SELECT TOP(1) @ZpvDrwTransNum = drt.trans_num + 1 FROM zpv_drawer_trans drt ORDER BY drt.trans_num DESC
	IF @ZpvDrwTransNum IS NULL SET @ZpvDrwTransNum = 1		
	
	SELECT 
		@ZpvDrwGlbankRowpointer = gl.RowPointer 
	FROM glbank_mst gl 
	WHERE 
		gl.zla_pay_id	= @ZpvCoPaymentArPayId AND 
		gl.check_num	= @ZpvCoPaymentCheckNum AND 
		gl.bank_code	= @ZpvCoPaymentBankCode
		
	IF @ZpvDrwGlbankRowpointer IS NULL
	BEGIN
		SET @Infobar = NULL
		EXEC @Severity = dbo.MsgAppSp @Infobar OUTPUT, 'E=NoExist0'
			, '@glbank'
		RETURN @Severity
	END		
			
	INSERT INTO [dbo].[zpv_drawer_trans]
       ([trans_num]
       ,[type]
       ,[relief_num]
       ,[trans_date]
       ,[packet]
       ,[drawer]
       ,[glbank_rowpointer]
       ,[copay_rowpointer]
       ,[amount]
       ,[curr_code]
       ,[exch_rate]
       ,[for_amount]
       ,[apply_date]
       ,[ar_type_id]
       ,[co_num])
	VALUES
       (@ZpvDrwTransNum			--trans_num, MatlTransNumType
       ,'T'						--type, varchar(1)
       ,null					--relief_num, MatlTransNumType
       ,GETDATE()				--trans_date, DateType
       ,null					--packet, varchar(15)
       ,@PDrawer				--drawer, varchar(15)
       ,@ZpvDrwGlbankRowpointer	--glbank_rowpointer, RowPointerType
       ,@ZpvCoPaymentRowPointer	--copay_rowpointer, RowPointerType
       ,@ZpvCoPaymentAmount		--amount, AmountType
       ,@ZpvCoPaymentCurrCode	--curr_code, CurrCodeType
       ,isnull(@ZpvCoPaymentExchRate,1)	--exch_rate, ExchRateType
       ,isnull(@ZpvCoPaymentForAmount,1) --for_amount, AmountType
       ,null					--apply_date, DateType
       ,@ZpvCoPaymentPayType	--ar_type_id, ZlaArTypeIdType
       ,@PCoNum)				--co_num, CoNumType	

	FETCH NEXT FROM PaymentCur
	INTO
		@ZpvCoPaymentPaySeq	
		, @ZpvCoPaymentPayType
		, @ZpvCoPaymentAmount
		, @ZpvCoPaymentRowPointer
		, @ZpvCoPaymentCurrCode	
		, @ZpvCoPaymentBankCode	
		, @ZpvCoPaymentExchRate 
		, @ZpvCoPaymentForAmount
		, @ZpvCoPaymentDrawer	
		, @ZpvCoPaymentArPayId	
		, @ZpvCoPaymentCheckNum

END
CLOSE PaymentCur
DEALLOCATE PaymentCur

RETURN @Severity


GO

