/****** Object:  StoredProcedure [dbo].[ZPV_GetNextCheckNumberSp]    Script Date: 10/29/2014 12:27:48 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ZPV_GetNextCheckNumberSp]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[ZPV_GetNextCheckNumberSp]
GO

/****** Object:  StoredProcedure [dbo].[ZPV_GetNextCheckNumberSp]    Script Date: 10/29/2014 12:27:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




/* $Header: /ApplicationDB/Stored Procedures/GetNextCheckNumberSp.sp 15    2/03/14 2:57p Tcecere $ */
/*
***************************************************************
*                                                             *
*                           NOTICE                            *
*                                                             *
*   THIS SOFTWARE IS THE PROPERTY OF AND CONTAINS             *
*   CONFIDENTIAL INFORMATION OF INFOR AND/OR ITS AFFILIATES   *
*   OR SUBSIDIARIES AND SHALL NOT BE DISCLOSED WITHOUT PRIOR  *
*   WRITTEN PERMISSION. LICENSED CUSTOMERS MAY COPY AND       *
*   ADAPT THIS SOFTWARE FOR THEIR OWN USE IN ACCORDANCE WITH  *
*   THE TERMS OF THEIR SOFTWARE LICENSE AGREEMENT.            *
*   ALL OTHER RIGHTS RESERVED.                                *
*                                                             *
*   (c) COPYRIGHT 2010 INFOR.  ALL RIGHTS RESERVED.           *
*   THE WORD AND DESIGN MARKS SET FORTH HEREIN ARE            *
*   TRADEMARKS AND/OR REGISTERED TRADEMARKS OF INFOR          *
*   AND/OR ITS AFFILIATES AND SUBSIDIARIES. ALL RIGHTS        *
*   RESERVED.  ALL OTHER TRADEMARKS LISTED HEREIN ARE         *
*   THE PROPERTY OF THEIR RESPECTIVE OWNERS.                  *
*                                                             *
*************************************************************** 
*/
/* $Archive: /ApplicationDB/Stored Procedures/GetNextCheckNumberSp.sp $
 *
 * $NoKeywords: $
 */
CREATE PROCEDURE [dbo].[ZPV_GetNextCheckNumberSp] (
	@BankCode BankCodeType,
	@PayType LongList,
	@NextCheckNumber GlCheckNumType OUTPUT
) AS

   -- Check for existence of Generic External Touch Point routine (this section was generated by SpETPCodeSp and inserted by CallETPs.exe):
   IF OBJECT_ID(N'dbo.EXTGEN_GetNextCheckNumberSp') IS NOT NULL
   BEGIN
      DECLARE @EXTGEN_SpName sysname
      SET @EXTGEN_SpName = N'dbo.EXTGEN_GetNextCheckNumberSp'
      -- Invoke the ETP routine, passing in (and out) this routine's parameters:
      EXEC @EXTGEN_SpName
         @BankCode
         , @PayType
         , @NextCheckNumber OUTPUT
 
      -- ETP routine must take over all desired functionality of this standard routine:
      RETURN 0
   END
   -- End of Generic External Touch Point code.
 
DECLARE
  @GlbankRowPointer  RowPointerType
, @GlbankCheckNum    GlCheckNumType
, @AppmtRowPointer   RowPointerType
, @AppmtCheckNum     GlCheckNumType
, @Severity          INT

SET @Severity = 0
SET @GlbankRowPointer = NULL
SET @GlbankCheckNum   = 0
SET @AppmtRowPointer  = NULL
SET @AppmtCheckNum    = 0

SELECT TOP 1
	@GlbankRowPointer = glbank.RowPointer,
	@GlbankCheckNum   = isnull(glbank.check_num,0)
FROM glbank
WHERE glbank.bank_code = @BankCode AND
	glbank.type = @PayType
ORDER BY glbank.check_num DESC

SELECT TOP 1
	@AppmtRowPointer = arpmt.RowPointer,
	@AppmtCheckNum   = isnull(arpmt.check_num,0)
FROM arpmt
WHERE arpmt.bank_code = @BankCode AND
	arpmt.[type] = @PayType
ORDER BY arpmt.check_num DESC

SET @NextCheckNumber = dbo.MaxQty(ISNULL(@GlbankCheckNum,0),ISNULL(@AppmtCheckNum,0)) + 1
SET @Severity = 0

GO

