/****** Object:  StoredProcedure [dbo].[ZPV_CLM_CustomerCreditLimitInfoSp]    Script Date: 11/06/2014 16:25:27 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ZPV_CLM_CustomerCreditLimitInfoSp]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[ZPV_CLM_CustomerCreditLimitInfoSp]
GO

/****** Object:  StoredProcedure [dbo].[ZPV_CLM_CustomerCreditLimitInfoSp]    Script Date: 11/06/2014 16:25:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


/* $Header: /ApplicationDB/Stored Procedures/ZBR_NfeInvoicingSp 1      */
/*
***************************************************************
*                                                             *
*                           NOTICE                            *
*                                                             *
*   THIS SOFTWARE IS THE PROPERTY OF AND CONTAINS             *
*   CONFIDENTIAL INFORMATION OF INFOR AND/OR ITS AFFILIATES   *
*   OR SUBSIDIARIES AND SHALL NOT BE DISCLOSED WITHOUT PRIOR  *
*   WRITTEN PERMISSION. LICENSED CUSTOMERS MAY COPY AND       *
*   ADAPT THIS SOFTWARE FOR THEIR OWN USE IN ACCORDANCE WITH  *
*   THE TERMS OF THEIR SOFTWARE LICENSE AGREEMENT.            *
*   ALL OTHER RIGHTS RESERVED.                                *
*                                                             *
*   (c) COPYRIGHT 2010 INFOR.  ALL RIGHTS RESERVED.           *
*   THE WORD AND DESIGN MARKS SET FORTH HEREIN ARE            *
*   TRADEMARKS AND/OR REGISTERED TRADEMARKS OF INFOR          *
*   AND/OR ITS AFFILIATES AND SUBSIDIARIES. ALL RIGHTS        *
*   RESERVED.  ALL OTHER TRADEMARKS LISTED HEREIN ARE         *
*   THE PROPERTY OF THEIR RESPECTIVE OWNERS.                  *
*                                                             *
***************************************************************
*/

/* $Archive: /ApplicationDB/Stored Procedures/ZPV_CLM_ARInvoicesToBePaySp $
 *
 * SL9.00.10 lbenetton Sat May 10 13:00:00 2013
 * Final Version 1.0.0
 * 
 * $NoKeywords: $
 */
CREATE PROCEDURE [dbo].[ZPV_CLM_CustomerCreditLimitInfoSp](
	@CustNum		CustNumType,
	@DeudaTotal				AmountType OUTPUT,
	@FacturasAVencer		AmountType OUTPUT,
	@FacturasVencidas		AmountType OUTPUT,
	@ChequesCartera			AmountType OUTPUT,
	@TotalPedidos			AmountType OUTPUT,
	@PedidosAutorizados		AmountType OUTPUT,
	@PedidosRetenidos		AmountType OUTPUT,
	@CobradosNoEntregados	AmountType OUTPUT)
 
AS
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

   -- Check for existence of Generic External Touch Point routine (this section was generated by SpETPCodeSp and inserted by CallETPs.exe):
   IF OBJECT_ID(N'dbo.EXTGEN_ZPV_CLM_ARInvoicesToBePaySp') IS NOT NULL
   BEGIN
      DECLARE @EXTGEN_SpName sysname
      SET @EXTGEN_SpName = N'dbo.EXTGEN_ZPV_CLM_ARInvoicesToBePaySp'
      -- Invoke the ETP routine, passing in (and out) this routine's parameters:
      EXEC @EXTGEN_SpName
			@CustNum,
			@DeudaTotal			OUTPUT,
			@FacturasAVencer	OUTPUT,
			@FacturasVencidas	OUTPUT,
			@ChequesCartera		OUTPUT,
			@TotalPedidos		OUTPUT,
			@PedidosAutorizados	OUTPUT,
			@PedidosRetenidos	OUTPUT,
			@CobradosNoEntregados	OUTPUT
 
      -- ETP routine must take over all desired functionality of this standard routine:
      RETURN 0
   END
   -- End of Generic External Touch Point code.

declare @tt_credit table(
	deuda_total			AmountType,
	facturas_avencer	AmountType,
	facturas_vencidas	AmountType,
	cheques_cartera		AmountType)

set @ChequesCartera = 0
set @CobradosNoEntregados = 0
set @DeudaTotal = 0
set @FacturasAVencer = 0
set @FacturasVencidas = 0
set @PedidosAutorizados = 0
set @PedidosRetenidos = 0
set @TotalPedidos = 0

insert into @tt_credit(
	deuda_total)
select 
	isnull((ar.amount + ar.sales_tax + ar.sales_tax_2 + ar.freight + ar.misc_charges),0) -
	isnull((select sum(n.amount) from artran_mst n 
		where	n.cust_num	= ar.cust_num 
			and n.type		= 'P'
			and n.apply_to_inv_num = ar.inv_num),0) -
	isnull((select sum(n.amount + n.sales_tax + n.sales_tax_2 + n.freight + n.misc_charges) from artran_mst n 
		where	n.cust_num	= ar.cust_num 
			and n.type		= 'C'
			and n.apply_to_inv_num = ar.inv_num),0) +
	isnull((select sum(n.amount + n.sales_tax + n.sales_tax_2 + n.freight + n.misc_charges) from artran_mst n 
		where	n.cust_num	= ar.cust_num 
			and n.type		= 'D'
			and n.apply_to_inv_num = ar.inv_num),0)
from artran_mst ar 
where	ar.cust_num = @CustNum
	and	ar.type		= 'I'
	and ar.active	= 1

insert into @tt_credit(
	facturas_avencer)
select 
	isnull((ar.amount + ar.sales_tax + ar.sales_tax_2 + ar.freight + ar.misc_charges),0) -
	isnull((select sum(n.amount) from artran_mst n 
		where	n.cust_num	= ar.cust_num 
			and n.type		= 'P'
			and n.apply_to_inv_num = ar.inv_num),0) -
	isnull((select sum(n.amount + n.sales_tax + n.sales_tax_2 + n.freight + n.misc_charges) from artran_mst n 
		where	n.cust_num	= ar.cust_num 
			and n.type		= 'C'
			and n.apply_to_inv_num = ar.inv_num),0) +
	isnull((select sum(n.amount + n.sales_tax + n.sales_tax_2 + n.freight + n.misc_charges) from artran_mst n 
		where	n.cust_num	= ar.cust_num 
			and n.type		= 'D'
			and n.apply_to_inv_num = ar.inv_num),0)
from artran_mst ar 
where	ar.cust_num = @CustNum
	and	ar.type		= 'I'
	and ar.active	= 1 
	and ar.due_date >= GETDATE()

insert into @tt_credit(
	facturas_vencidas)
select 
	isnull((ar.amount + ar.sales_tax + ar.sales_tax_2 + ar.freight + ar.misc_charges),0) -
	isnull((select sum(n.amount) from artran_mst n 
		where	n.cust_num	= ar.cust_num 
			and n.type		= 'P'
			and n.apply_to_inv_num = ar.inv_num),0) -
	isnull((select sum(n.amount + n.sales_tax + n.sales_tax_2 + n.freight + n.misc_charges) from artran_mst n 
		where	n.cust_num	= ar.cust_num 
			and n.type		= 'C'
			and n.apply_to_inv_num = ar.inv_num),0) +
	isnull((select sum(n.amount + n.sales_tax + n.sales_tax_2 + n.freight + n.misc_charges) from artran_mst n 
		where	n.cust_num	= ar.cust_num 
			and n.type		= 'D'
			and n.apply_to_inv_num = ar.inv_num),0)
from artran_mst ar 
where	ar.cust_num = @CustNum
	and	ar.type		= 'I'
	and ar.active	= 1 
	and ar.due_date < GETDATE()	

insert into @tt_credit(
	cheques_cartera)
select SUM(amount) from artran_mst ar
inner join glbank_mst gl on		ar.bank_code = gl.bank_code
						and ar.inv_seq = gl.cust_check_num
inner join bank_hdr_mst bh on bh.bank_code = gl.bank_code
		
		where	ar.type = 'P'
				and bh.zla_bank_type = 'T'
				and gl.type = 'D'
				and gl.voided = 0
				and gl.zla_deposit_applied = 0
				and ar.cust_num = @CustNum
	

select
	@DeudaTotal =  sum(isnull(deuda_total,0)),
	@FacturasAVencer =  sum(isnull(facturas_avencer,0)),
	@FacturasVencidas =  sum(isnull(facturas_vencidas,0)),
	@ChequesCartera =  sum(isnull(cheques_cartera,0))
from @tt_credit		


GO

